# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:

  build-snapshot:
    dir: cmd/koios-rest
    desc: |
      Build snapshot binaries to ./cmd/koios-rest/dist.
    cmds:
      - goreleaser release --snapshot --rm-dist

  cover:
    desc: Open the cover tool
    cmds:
      - go tool cover -html=coverage.txt

  gen:testdata:
    desc: Updates testdata in testdata directory.
    dir: internal/testdatagen
    cmds:
      - go run . ../../testdata

  goreleaser:
    desc: Run GoReleaser either in snapshot or release mode
    dir: cmd/koios-rest
    deps:
      - build
    vars:
      SNAPSHOT:
        sh: 'if [[ $GITHUB_REF != refs/tags/v* ]]; then echo "--snapshot"; fi'
    cmds:
      - goreleaser release --rm-dist {{.SNAPSHOT}}

  lint:
    desc: Lint the code with golangci-lint
    cmds:
      - golangci-lint run ./... --fix

  print:next:
    desc: |
      Prints next version based on Conventional Commits spec.
    cmds:
      - svu n

  # https://github.com/caarlos0/svu
  release:
    dir: cmd/koios-rest
    vars:
      NEXT:
        sh: svu n
    desc: |
      Release new version, you must be maintainer
      and have GITHUB_TOKEN env set e.g. in (.env) file.
    cmds:
      - git tag -sm"{{.NEXT}}" {{.NEXT}}
      - git push
      - git push --tags

  setup:
    desc: Setup development env.
    cmds:
      - task: setup:repo
      - task: setup:cmd

  setup:repo:
    cmds:
      - go mod download

  setup:cmd:
    dir: cmd/koios-rest
    cmds:
      - go mod download

  test:
    desc: Run tests
    env:
      LC_ALL: C
    vars:
      TEST_OPTIONS: '{{default "" .TEST_OPTIONS}}'
      SOURCE_FILES: '{{default "./..." .SOURCE_FILES}}'
      TEST_PATTERN: '{{default "." .TEST_PATTERN}}'
    cmds:
      - go test {{.TEST_OPTIONS}} -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt {{.SOURCE_FILES}} -run {{.TEST_PATTERN}} -timeout=5m
