name: guild

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  KOIOS_NETWORK: guild

jobs:
  network:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - transactions
    strategy:
      matrix:
        test:
         - NetworkTip
         - NetworkGenesis
         - NetworkTotals
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  epoch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
         - EpochInfo
         - EpochParams
         - EpochBlockProtocols
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  blocks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
         - Blocks
         - BlockInfo
         - BlockTxs
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  transactions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
         - TxInfo
         - TxUTxO
         - TxMetadata
         - TxMetaLabels
         - TxStatus
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  address:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - epoch
    strategy:
      matrix:
        test:
         - AddressInfo
         - AddressTxs
         - AddressAssets
         - CredentialTxs
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  account:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - blocks
    strategy:
      matrix:
        test:
         - Accounts
         - AccountInfo
         - AccountRewards
         - AccountUpdates
         - AccountAddresses
         - AccountAssets
         - AccountHistory
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  assets:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - account
    strategy:
      matrix:
        test:
         - Assets
         - AssetAddresses
         - AssetInfo
         - AssetHistory
         - AssetPolicyInfo
         - AssetSummary
         - AssetTxs
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK

  pool:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - address
    strategy:
      matrix:
        test:
         - Pools
         - PoolSnapshot
         - PoolInfo
         - PoolDelegators
         - PoolDelegatorsHistory
         - PoolBlocks
         - PoolHistory
         - PoolUpdates
         - PoolRelays
         - PoolMetadata
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK
  scripts:
    runs-on: ubuntu-latest
    needs:
      # just to limit concurrent check groups to 3
      - address
    strategy:
      matrix:
        test:
         - NativeScriptList
         - PlutusScriptList
         - ScriptRedeemers
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -v -covermode atomic -coverprofile coverage.txt -run  Test${{ matrix.test }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: "${{ env.KOIOS_NETWORK }},${{ github.job }},${{ matrix.test }}"
          name: "${{ env.KOIOS_NETWORK }}-${{ github.job }}-${{ matrix.test }}"
          files: ./coverage.txt
          env_vars: KOIOS_NETWORK
