name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # https://github.com/actions/setup-go/issues/191
        version: ['1.16', '1.17']
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -failfast -race  ./... -timeout=5m

