name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: ['1.16', '1.17', '1.18.0-rc.1']
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          stable: false
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -failfast -race  ./... -timeout=5m

